# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with and , the first terms will be:
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def calculate_fibonacci(max):
    cur = 1
    prev = 0
    sum = 0
    while ( cur + prev < max):
        save = cur + prev
        prev = cur
        cur = save
        sum += cur
        # print (cur) 
    print(sum)
        
calculate_fibonacci(4000000)